version: '2'

services:
  mongodb:
    container_name: mongodb
    image: 'docker.io/bitnami/mongodb:4.0'
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - MONGODB_ROOT_PASSWORD=secret

volumes:
  mongodb_data:
    driver: local
